apiVersion: v1
kind: Service
metadata:
  name: {{ include "vulntrack.backend.name" . }}
  labels:
    {{- include "vulntrack.labels" . | nindent 4 }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    {{- include "vulntrack.selector" (dict "root" . "component" "backend") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
