apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vulntrack.backend.name" . }}
  labels:
    {{- include "vulntrack.labels" . | nindent 4 }}
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ include "vulntrack.postgres.name" . }}:{{ .Values.postgres.service.port }}/{{ .Values.postgres.database }}"
  SERVER_PORT: {{ .Values.backend.service.port | quote }}
  {{- range $k, $v := .Values.backend.config }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
