apiVersion: v1
kind: Service
metadata:
  name: {{ include "vulntrack.postgres.name" . }}
  labels:
    {{- include "vulntrack.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "vulntrack.selector" (dict "root" . "component" "postgres") | nindent 4 }}
  ports:
    - name: postgres
      port: {{ .Values.postgres.service.port }}
      targetPort: postgres
